In [ ]:
import tensorflow as tf
#creating a constant tensor
a=tf.constant([[1,2],[3,4]])
print(a)



tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#creating a tensor withall zeros
b=tf.zeros([3,4])
print(b)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
#creating a tensor with all ones
c=tf.ones([2,3])
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
#create constant tensors
a=tf.constant(2)
b=tf.constant(3)
print('Tensor a:',a)
print('Tensor b:',b)

Tensor a: tf.Tensor(2, shape=(), dtype=int32)
Tensor b: tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
#add 2 tensors
c=tf.add(9,7)
print('Addition:',c)

Addition: tf.Tensor(16, shape=(), dtype=int32)


In [ ]:
#multiply 2 tensors
p=tf.multiply(9,7)
print('Multiplication:',p)

Multiplication: tf.Tensor(63, shape=(), dtype=int32)


In [ ]:
#divide 2 tensors
d=tf.divide(9,7)
print('Division:',d)

Division: tf.Tensor(1.2857142857142858, shape=(), dtype=float64)


In [ ]:
#matrix multiplication
#create 2D matrices

matrix1= tf.constant([[1,2],[3,4]])
matrix2= tf.constant([[5,6],[7,8]])
matrix_product=tf.matmul(matrix1,matrix2)
print('matrix multiplication:\n',matrix_product)

matrix multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
#create a variable
x=tf.Variable(5.0)
#Add to the variable
x.assign_add(12.0)
print('Updated variable:',x)


Updated variable: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=17.0>


In [ ]:
#create a variable
x=tf.Variable(10.0)
#Define a function
with tf.GradientTape() as tape:

  y=x**2
dy_dx=tape.gradient(y,x)
print('Gradient of y with respect to x:',dy_dx)

Gradient of y with respect to x: tf.Tensor(20.0, shape=(), dtype=float32)


##

In [ ]:
a=tf.constant([1,2,3])
b=tf.constant(10)

#Add using broadcasting
result=tf.add(a,b)
print('Broadcasing addition:',result)

Broadcasing addition: tf.Tensor([11 12 13], shape=(3,), dtype=int32)


In [ ]:
#create a tensor
tensor=tf.constant([[1,2,3],[4,5,6]])
#sum of all elements
sum_all=tf.reduce_sum(tensor)
print('sum of all elements:',sum_all)

sum of all elements: tf.Tensor(21, shape=(), dtype=int32)


In [ ]:
# sum along an axis
sum_axis_0 = tf.reduce_sum(tensor,axis=0)
print('sum along axis 0:', sum_axis_0)

sum along axis 0: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
#reshape tensor
reshaped_tensor =tf.reshape(tensor,[3,2])
print('Reshaped Tensor:\n',reshaped_tensor)

Reshaped Tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
transposed_tensor =tf.transpose(tensor)
print('Transposed tensor:\n',transposed_tensor)

Transposed tensor:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:
squared= tf.pow(tensor,2)

print('Element wise power:\n',squared)

Element wise power:
 tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


In [3]:
import numpy as np
import tensorflow as tf
#create a Numpy array
numpy_array=np.array([[1,3],[3,4]])
#convert the Numpy array to a tensorflow tensor
tensor=tf.convert_to_tensor(numpy_array,dtype=tf.float32)
#perform tensorflow operation on the tensor
result=tf.matmul(tensor,tensor)
print('original numpy array:\n',numpy_array)
print('converted tensor flow tensor:\n ',tensor)
print('Matrix multiplication result:\n',result)
#convert the result tensor back to a numpy array
numpy_result=result.numpy()
print('converted back to Numpy:\n',numpy_result)

original numpy array:
 [[1 3]
 [3 4]]
converted tensor flow tensor:
  tf.Tensor(
[[1. 3.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Matrix multiplication result:
 tf.Tensor(
[[10. 15.]
 [15. 25.]], shape=(2, 2), dtype=float32)
converted back to Numpy:
 [[10. 15.]
 [15. 25.]]


In [13]:
import numpy as np
from tensorflow.keras import layers, models
# generate the dataset for addition

#create two random numbers as inputs and their sum as the target
def generate_addition_data(samples=10000):
  x1=np.random.randint(0,100,size=(samples,))
  x2=np.random.randint(0,100,size=(samples,))
  y=x1=x2
  return np.column_stack((x1,x2)),y
#generate training and testing date
x_train,y_train = generate_addition_data(10000)
x_test,y_test = generate_addition_data(1000)
  #Build the neural network model
model=models.Sequential()
  #input layer:takes 2 input values (x1,x2)
model.add(layers.Dense(64,activation='relu',input_shape=(2,)))
  #hidden layer
model.add(layers.Dense(64,activation='relu'))
  #output layer:predicts a single value(the sum)
model.add(layers.Dense(1))
  #compile the model
model.compile(optimizer='adam',loss='mean_squared_error')
  #train the model
model.fit(x_train,y_train,epochs=50,batch_size=32,validation_split=0.2)
  #evalute the model
test_loss = model.evaluate(x_test,y_test)
  #test the model with new data
test_data =np.array([[10,20],[50,60],[23,45]])
predictions= model.predict(test_data)
print('test  data:',test_data)

Epoch 1/50


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 588.7043 - val_loss: 0.0101
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0097 - val_loss: 0.0079
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0069 - val_loss: 1.3849e-04
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3.8993e-05 - val_loss: 2.1356e-05
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.6527e-05 - val_loss: 5.8535e-05
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.4787e-05 - val_loss: 1.7951e-05
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.9947e-04 - val_loss: 1.3107e-05
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0751e-05 - val_loss: 3.9456e-06
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.0688e-04 - val_loss: 1.2034e-04
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.7395e-05 - val_loss: 1.5899e-06
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.1930e-06 - val_loss: 1.26

# PYTORCH

In [14]:
#addition using Pytorch
import torch
#create 2 arrays(tensors)
array1=torch.tensor([1,2,3,4,5])
array2=torch.tensor([10,20,30,40,50])
#peform element wise addition
result =array1+array2
#print the arrays and their sum
print ('Array1:',array1)
print('Array2:',array2)
print('sum:',result)

Array1: tensor([1, 2, 3, 4, 5])
Array2: tensor([10, 20, 30, 40, 50])
sum: tensor([11, 22, 33, 44, 55])


In [16]:
#Basic arithmetic operations

a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

#element_wise addition

add_result = a+b

#element_wise subtraction

sub_result =a-b

#element_wise multiplication

mul_result =a*b

#element_wise division

div_result =a/b

print('Addition:', add_result)
print('Subtraction:', sub_result)
print('Multiplication:',mul_result)
print('Division:',div_result)




Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


Matrix operations


In [18]:
#Define two 2D tensors(matrices)
matrix1 =torch.tensor([[1,2],[3,4]])
matrix2 =torch.tensor([[5,6],[7,8]])
#matrix multiplications

matmul_result =torch.matmul(matrix1,matrix2)

#matrix transpose

transpose_result =matrix1.t()

#dot productn(ID tensors)

vec1 =torch.tensor([1,2])
vec2 =torch.tensor([3,4])

dot_result= torch.dot(vec1, vec2)

print ('Matrix multiplication:',matmul_result)
print('Transpose:', transpose_result)
print('Dot product:', dot_result)

Matrix multiplication: tensor([[19, 22],
        [43, 50]])
Transpose: tensor([[1, 3],
        [2, 4]])
Dot product: tensor(11)
